# This is a basic workflow to help you get started with Actions

name: prod-full-app-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Installs Angular and Node.js
      - name: Installation of Angular
        run: |
          sudo apt-get install software-properties-common
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install nodejs
          npm install -g @angular/cli
          npm install -g --save-dev @angular-devkit/build-angular
      
      # Runs frontend app build
      - name: Run frontend app build
        run: |
          cd dictionaryclient
          ng build --verbose
      
      # Runs backend app build
      - name: Run backend app build
        run: mvn clean install -DskipTests

      
